services:
  docs:
    image: local/trans-archive:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SITE_URL=${SITE_URL}
        - REPO_URL=${REPO_URL}
        - EDIT_URI=${EDIT_URI}
        - ONION_LOCATION=${ONION_LOCATION}
    container_name: trans-archive
    restart: unless-stopped
    ports:
      - "8080:80"
